repos:
  - repo: local
    hooks:
      - id: commit-msg-prefix
        name: Commit msg deve iniciar com API-<numero>
        language: system
        entry: bash -c 'if ! grep -qE "^API-(100|[1-9][0-9]?|[1-9])" "$1"; then echo "Erro-> Commit deve começar com API-XXX (ex-> API-81)"; exit 1; fi'
        args: [".git/commit-msg"]
        stages: [commit-msg]
        pass_filenames: true
        
      - id: lint
        name: Lint staged files
        language: system
        entry: bash -c 'npx eslint --ext .js,.ts,.vue $(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(js|ts|vue)$" || true)'
        stages: [pre-commit]