name: CI-Front
on:
  pull_request:
    branches:
      - "API-**"
      - develop
      - "sprint-**"
      - main
  push:
    branches:
      - "API-**"
      - develop
      - "sprint-**"
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Debug coverage output
        run: |
          echo "Coverage directory contents:"
          ls -la coverage/
          echo "Looking for lcov.info:"
          find coverage/ -name "lcov.info" -type f || echo "lcov.info not found"
          if [ -f coverage/lcov.info ]; then
            echo "First 10 lines of lcov.info:"
            head -10 coverage/lcov.info
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-frontend
          path: coverage

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt
        run: npm run build

      - name: Show build output (debug)
        run: |
          echo "Listing repo root:"
          ls -la
          echo "Listing .output (if exists):"
          ls -la ./.output || echo ".output not found"

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-build
          path: ./.output
          if-no-files-found: warn

  sonarqube:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: coverage-frontend
          path: coverage
      
      - name: Debug downloaded coverage
        run: |
          echo "Downloaded coverage files:"
          ls -la coverage/
          echo "Looking for lcov.info:"
          find coverage/ -name "lcov.info" -type f || echo "lcov.info not found"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}